import cv2
from ultralytics import RTDETR

def main():
    print("===========================================")
    print("      Initializing Live PPE Live Test      ")
    print("===========================================")

    # Point to the weights generated by your training session
    model_path = 'C:/Users/hsmsa/runs/detect/ppe_training_results/rtdetr_frontview_800px/weights/best.pt'
    
    print(f"[INFO] Loading model from: {model_path}")
    model = RTDETR(model_path)

    # Initialize the webcam
    cap = cv2.VideoCapture(0)
    
    print("[INFO] Webcam active. Put on your PPE!")
    print("[INFO] Press 'Q' to shut down the feed.")

    while cap.isOpened():
        success, frame = cap.read()
        if not success:
            print("[ERROR] Failed to grab frame from camera.")
            break

        # Run inference. The conf=0.45 threshold filters out all the background noise
        results = model(frame, stream=True, conf=0.45)

        for r in results:
            # Ultralytics handles the bounding box and label rendering automatically
            annotated_frame = r.plot()

            # Display the live feed
            cv2.imshow("Smart PPE Detection - Python Test", annotated_frame)

        # Listen for the 'q' key to quit
        if cv2.waitKey(1) & 0xFF == ord('q'):
            print("\n[INFO] Shutting down...")
            break

    # Release hardware resources
    cap.release()
    cv2.destroyAllWindows()

if __name__ == '__main__':
    main()